version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-app
    container_name: laravel_app
    ports:
      - 8000:80
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=news_aggregator
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - MEILISEARCH_HOST=http://meilisearch:7700 # Meilisearch host bilgisi
    volumes:
      - .:/var/www/html
    depends_on:
      - db
      - redis
      - meilisearch # Meilisearch servisine bağımlılık ekleniyor

  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: news_aggregator
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql_db
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - 8080:80
    depends_on:
      - db

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - 6379:6379

  meilisearch:
    image: getmeili/meilisearch:latest
    container_name: meilisearch
    ports:
      - 7700:7700
    volumes:
      - meilisearch-data:/meili_data

volumes:
  db-data:
  meilisearch-data:
