version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-app
    container_name: laravel_app
    ports:
      - 8000:80
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=base64:++68j+4Gr0+ItQqUoZwUT0C/QfZPbY2l2Hzb+5K4/FA=
      - DB_CONNECTION=pgsql
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=laravel
      - DB_USERNAME=postgres
      - DB_PASSWORD=secret
    volumes:
      - .:/var/www/html
    depends_on:
      - db
      - redis

  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: news_aggregator
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql_db
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - 8080:80
    depends_on:
      - db

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - 6379:6379

volumes:
  db-data:
